name: scanner-cron

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch: {}

jobs:
  run-scanner:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7
        ports: ["6379:6379"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install deps
        working-directory: services/scanner
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run scanner
        env:
          REDIS_URL: redis://localhost:6379/0
          BITGET_API_KEY: ${{ secrets.BITGET_API_KEY }}
          BITGET_SECRET: ${{ secrets.BITGET_SECRET }}
        run: |
          python src/main.py
      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: reports/ || true
